### ISSUE TITLE
Describe GitHub workflow: create a patch from pull request to r-devel/r-svn

### ISSUE THREAD

**Issue by krlmlr** [r-devel/rdevguide#23]
I'd argue that with https://github.com/r-devel/r-svn/ we no longer need to understand SVN to submit a patch to the Bugzilla system. It also brings the huge advantage that the patch is tested by GitHub Actions on all/most/many operating systems. Would you support splitting the patch submission chapter into two parts -- the SVN way and the GitHub way?

This is what the GitHub way roughly looks like:

- fork and clone repository
- create a branch, implement your changes
- push
- create a pull request
- wait for CI builds
- if CI builds fail, push more commits
- rinse and repeat until builds succeed
- send link to PR and link to patch to Bugzilla, the patch can be created directly from GitHub
- R core can review the patch on GitHub or in its text form
- If changes are needed, you can push again on GitHub, links will update automatically

CC @jeroen @lionel-.

**Comment by hturner** [comment]
Very happy to go in this direction. We thought it was best to begin by documenting the official workflow before documenting alternatives, but we recognise the advantage of CI/CD and that many developers will be more comfortable using GitHub. If you/others cc'd have time to contribute a PR with these changes in the coming weeks that would be great.

cc @lawremi @SaranjeetKaur

**Comment by llrs** [comment]
With the new github requirement to manually [approve each new author of a PR to run Github Actions](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/), is this scalable? The volume of PR to approve will be low but not sure how many people can approve github actions on that repository.

**Comment by gmbecker** [comment]
I have the same issue with this as @llrs, I think this is something to support established collaborations/collaborators with additional testing, but I don't know if it is going to be the "way forward".

Also, I should say that AFAIK engagement with R-core (as a whole) on bugs/issues/patches will continue to be on Bugzilla (which requires an svn patch), NOT on that github repo. So the review won't happen there, and shoudln't because that will fragment it.

That said, having used it its a super useful additional resource for testing.

**Comment by krlmlr** [comment]
@hturner: I hear that, the official workflow feels to me like a really big hurdle for newcomers though. Maybe an entirely new section/part called "Modern shortcuts" though, with references back and forth, and motivation why these may be better?

@llrs: Very good point, haven't thought about that.

@jeroen: Would you mind setting up teams in this organization:

- one team of trusted admins to increase the bus factor
- one team with write access to r-svn (but without push access to the main branch(es)) so that PRs don't need to be approved for members of that team?
    - Approving PRs manually is possible too, but then these PRs aren't usually merged, so we'd need to approve each and every PR which isn't sustainable indeed.

@gmbecker: GitHub PRs can be translated to SVN-compatible patches, e.g.:

- https://github.com/r-devel/r-svn/pull/31
- https://github.com/r-devel/r-svn/pull/31.diff: plain diff, condensed
- https://github.com/r-devel/r-svn/pull/31.patch: extended patch, one per commit, with commit metadata

That PR of mine got merged within a few days, BTW -- a pleasant surprise. R Core was able to pick it up from the URLs I provided.

**Comment by gmbecker** [comment]
@krlmlr I am aware of that, but it isn't the main point i was making. Most of R-core is not watching that repo as far as I know which means it is not an appropriate place to put things up for discussion or wider consideration within the R-core team. Yes, some of them are watching it and can choose to apply patches they see and like but that isn't the same thing that bugzilla provides (where, for better and worse, ever active R-core member gets email whenever anything happens).

Encouraging people to do things that are more convenient for them but less convenient for R-core is, in my humble opinion, not what the guide should be doing.

**Comment by krlmlr** [comment]
Can we still edit the patch on GitHub and discuss it in Bugzilla? That was the intention of my original proposal at least.

**Comment by gmbecker** [comment]
Fragmenting where the patches live and where the discussion happens seems
problematic to me. I think patches live and are discussed on bugzilla and
that repo (which again, I have used) is only used to test patches, not to
submit them and not as a place to discuss them.

**Comment by krlmlr** [comment]
I hear you, and I understand your concerns regarding fragmentation. I agree that the discussion itself should be kept on Bugzilla. There are advantages of keeping the patches on GitHub though:

- The contents of the patch are consistent with the test run;
- We can link to individual changesets of a GitHub PR, these links are permanent

Especially the first advantage is worth a bit of fragmentation IMO.

I see the following challenges:

- Appending `.diff` to the PR URL does not give a permanent link, the patch may change over time, and this would not be reflected in the Bugzilla discussion
- There might be advantages of hosting the patch on Bugzilla, e.g. automation available in this case (like "merging a pull request")

One way to solve the first challenge is to avoid the reuse of pull requests: if a patch is rejected, close the PR before pushing to the branch, and open a new one when done.

To wrap up: can we suggest

- using the GitHub repo for testing
- using it also for generating patches
- keeping discussion of patches on Bugzilla
- opening a new pull request for every patch shared on Bugzilla
- uploading a `.patch` file to Bugzilla only if asked

?

**Comment by gmbecker** [comment]
> I hear you, and I understand your concerns regarding fragmentation. I agree that the discussion itself should be kept on Bugzilla. There are advantages of keeping the patches on GitHub though:
> 
> * The contents of the patch are consistent with the test run;
> * We can link to individual changesets of a GitHub PR, these links are permanent
> 
> Especially the first advantage is worth a bit of fragmentation IMO.

So here is the thing. I think it is important to frame our collaborations with R-core as us coming to them. Teaching novice contributors to expect R-core members to come to us, rather than teaching them to do the legwork to go to R-core is not what I believe the guide should be doing.

I understand why you, and  very notably Jenny Bryan and probably many others wish the R sources and issues were tracked on github/gitlab/whatever. I do. I don't even disagree that things would be better for novices - and many of the rest of us-  in some senses if that was the case.

***But*** it is not the case and it is not our call to make, it is R-core's. When you want to collaborate with R-core, you go to the place that R-core uses for such collaborations. We can try to convince R-core to migrate the R sources to something with amore modern collaboration API. I know Jenny has been doing so for some years now. 

But absent success in such an endeavor, we need to teach novice contributors how to succsesfully collaborate with R-core now. And right now, I believe, and have had what I think is a great deal of success with, doing my own work however and wherever I want (ie on github) but all interactions, submissions for R-core to review, and discussions occur on bugzilla.

Another way to phrase this that I mention in the Contributing to R is that our job as collaborators with R-core is to make as little extra work for them as we can while still achieving our objective for the collaboration. Generally a moderate of extra work for R-core members per issue/bug is NOT worth it, even at fairly big savings to the submitter, because R-core members are collectively dealing with ALL the bugs, whereas the submitter is only dealing with one/a few.

And keep in mind, even with that mode of working, the linked repo is a fantastic testing resource that eases a major difficulty regarding other operating systems. As I said, I ahve used, it, and intend to continue to use it.

> To wrap up: can we suggest
> 
> * using the GitHub repo for testing
> * using it also for generating patches
> * keeping discussion of patches on Bugzilla
> * opening a new pull request for every patch shared on Bugzilla
> * uploading a `.patch` file to Bugzilla only if asked

In particular, this seems backwards for at least some versions of collaboration. If a patch has been written and tested, that is an important part of the discussion. In fact, I have had multiple patches go through one or more rounds of iteration based on discussions in bugzilla.

**Comment by krlmlr** [comment]
What do you mean by "writing and testing a patch"?

AFAICT, my proposed workflow adds no extra burden to R core. Bugzilla is the communication device, patches can be reviewed and applied pretty much the same way as if they came from an SVN checkout, a recursive diff, or were carefully written by hand. What am I missing?

**Comment by lionel-** [comment]
Gabe makes a good point about fragmenting discussion. At the same time, it is often useful to get feedback from other developers before submitting a patch, especially since it can be intimidating. Personally I open github PRs and ask for internal feedback before submitting a patch to bugzilla or by mail. So I don't think we should discourage github discussions of patches but we should encourage including a summary of the important points discussed on github (if any) in the submission.

I agree that it's best to create an actual patch and submit it instead of sending a github link (even it's a diff/patch URL). git is a great way of creating patches, I haven't used any other tool so far.

**Comment by krlmlr** [comment]
External feedback is a good point. Does the following make more sense:

- use the GitHub repo for testing and code review from "everyone" (=not only R core)
- download the patch from the `.diff` URL
- open/update a ticket in Bugzilla, attach the patch and the most important findings from the GitHub discussion
- if necessary, rinse and repeat the entire workflow (=update the PR on GitHub based on Bugzilla findings)

**Comment by elinw** [comment]
I really think this is the easiest way to work and is absolutely the way I would teach a beginner. If you are submitting a patch or diff file it does not matter how you produced it.

**Comment by hturner** [comment]
Closed by #110
